In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd
top3_cities_df = pd.read_csv('/content/drive/MyDrive/820_Project_cleaned_dataset.csv')
top3_cities_df.head()

,review_id,user_id,business_id,stars_review,useful,funny,cool,text,date,name,...,compliment_cool,compliment_funny,compliment_writer,compliment_photos,active_years,elite_count,elite_flag,friends_count,compliment_total,cluster
0,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,...,0,0,0,0,11.131507,0,0,1,1,1
1,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,1,2,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31,Dmitri's,...,0,0,0,0,10.723288,0,0,1,1,0
2,l3Wk_mvAog6XANIuGQ9C7Q,ZbqSHbgCjzVAqaa7NKWn5A,EQ-TZ2eeD_E0BHuvoaeG5Q,4,0,0,0,"Locals recommended Milktooth, and it's an amaz...",2015-08-19 14:31:45,Milktooth,...,0,0,0,0,9.556164,0,0,1,0,1
3,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4,0,0,0,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14,LaScala's,...,1,1,0,0,15.438356,0,0,44,8,3
4,OAhBYw8IQ6wlfw1owXWRWw,1C2lxzUo1Hyye4RFIXly3g,BVndHaLihEYbr76Z0CMEGw,5,0,0,0,"Great place for breakfast! I had the waffle, w...",2014-10-11 16:22:06,Mamas Kitchen,...,0,0,0,0,11.613699,0,0,3,0,3

In [5]:
top3_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1369708 entries, 0 to 1369707
Data columns (total 49 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   review_id           1369708 non-null  object
 1   user_id             1369708 non-null  object
 2   business_id         1369708 non-null  object
 3   stars_review        1369708 non-null  int64
 4   useful              1369708 non-null  int64
 5   funny               1369708 non-null  int64
 6   cool                1369708 non-null  int64
 7   text                1369708 non-null  object
 8   date                1369708 non-null  object
 9   name                1369708 non-null  object
 10  address             1365077 non-null  object
 11  city                1369708 non-null  object
 12  state               1369708 non-null  object
 13  postal_code         1369523 non-null  float64
 14  latitude            1369708 non-null  float64
 15  longitude           1369708 non-null  float64
 16  stars_business      1369708 non-null  float64
 17  review_count        1369708 non-null  int64
 18  is_open             1369708 non-null  int64
 19  attributes          1367949 non-null  object
 20  categories          1369708 non-null  object
 21  hours               1369708 non-null  object
 22  name_user           1369707 non-null  object
 23  review_count_user   1369708 non-null  int64
 24  yelping_since       1369708 non-null  object
 25  useful_user         1369708 non-null  int64
 26  funny_user          1369708 non-null  int64
 27  cool_user           1369708 non-null  int64
 28  elite               453202 non-null   object
 29  friends             1087264 non-null  object
 30  fans                1369708 non-null  int64
 31  average_stars       1369708 non-null  float64
 32  compliment_hot      1369708 non-null  int64
 33  compliment_more     1369708 non-null  int64
 34  compliment_profile  1369708 non-null  int64
 35  compliment_cute     1369708 non-null  int64
 36  compliment_list     1369708 non-null  int64
 37  compliment_note     1369708 non-null  int64
 38  compliment_plain    1369708 non-null  int64
 39  compliment_cool     1369708 non-null  int64
 40  compliment_funny    1369708 non-null  int64
 41  compliment_writer   1369708 non-null  int64
 42  compliment_photos   1369708 non-null  int64
 43  active_years        1369708 non-null  float64
 44  elite_count         1369708 non-null  int64
 45  elite_flag          1369708 non-null  int64
 46  friends_count       1369708 non-null  int64
 47  compliment_total    1369708 non-null  int64
 48  cluster             1369708 non-null  int64
dtypes: float64(6), int64(27), object(16)
memory usage: 512.1+ MB

In [6]:
# deal with na
top3_cities_df = top3_cities_df.dropna(subset=['text'])

# preprocessing
top3_cities_df['address'] = top3_cities_df['address'].fillna('Unknown')
top3_cities_df['postal_code'] = top3_cities_df['postal_code'].astype(str).fillna('Unknown')
top3_cities_df['attributes'] = top3_cities_df['attributes'].fillna('{}')
top3_cities_df['friends'] = top3_cities_df['friends'].fillna('')
top3_cities_df['elite'] = top3_cities_df['elite'].fillna('')
top3_cities_df = top3_cities_df[top3_cities_df['text'].str.strip() != '']

print(top3_cities_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1369708 entries, 0 to 1369707
Data columns (total 49 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   review_id           1369708 non-null  object
 1   user_id             1369708 non-null  object
 2   business_id         1369708 non-null  object
 3   stars_review        1369708 non-null  int64
 4   useful              1369708 non-null  int64
 5   funny               1369708 non-null  int64
 6   cool                1369708 non-null  int64
 7   text                1369708 non-null  object
 8   date                1369708 non-null  object
 9   name                1369708 non-null  object
 10  address             1369708 non-null  object
 11  city                1369708 non-null  object
 12  state               1369708 non-null  object
 13  postal_code         1369708 non-null  object
 14  latitude            1369708 non-null  float64
 15  longitude           1369708 non-null  float64
 16  stars_business      1369708 non-null  float64
 17  review_count        1369708 non-null  int64
 18  is_open             1369708 non-null  int64
 19  attributes          1369708 non-null  object
 20  categories          1369708 non-null  object
 21  hours               1369708 non-null  object
 22  name_user           1369707 non-null  object
 23  review_count_user   1369708 non-null  int64
 24  yelping_since       1369708 non-null  object
 25  useful_user         1369708 non-null  int64
 26  funny_user          1369708 non-null  int64
 27  cool_user           1369708 non-null  int64
 28  elite               1369708 non-null  object
 29  friends             1369708 non-null  object
 30  fans                1369708 non-null  int64
 31  average_stars       1369708 non-null  float64
 32  compliment_hot      1369708 non-null  int64
 33  compliment_more     1369708 non-null  int64
 34  compliment_profile  1369708 non-null  int64
 35  compliment_cute     1369708 non-null  int64
 36  compliment_list     1369708 non-null  int64
 37  compliment_note     1369708 non-null  int64
 38  compliment_plain    1369708 non-null  int64
 39  compliment_cool     1369708 non-null  int64
 40  compliment_funny    1369708 non-null  int64
 41  compliment_writer   1369708 non-null  int64
 42  compliment_photos   1369708 non-null  int64
 43  active_years        1369708 non-null  float64
 44  elite_count         1369708 non-null  int64
 45  elite_flag          1369708 non-null  int64
 46  friends_count       1369708 non-null  int64
 47  compliment_total    1369708 non-null  int64
 48  cluster             1369708 non-null  int64
dtypes: float64(5), int64(27), object(17)
memory usage: 512.1+ MB
None

**In this part, we first processed all the parts of the data text that need to be cleaned, so that it will be more convenient to run the model later.**

In [7]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

ps = PorterStemmer()

# Tokenize + Lemmatize
def tokenize_lemmatize(sentence):
    tokens = word_tokenize(sentence)  # Tokenize
    lemmatized_tokens = [ps.stem(word) for word in tokens]  # Lemmatize
    return lemmatized_tokens

#BoW
cv = CountVectorizer(tokenizer=tokenize_lemmatize)
# train model
top3_cities_df_sample = top3_cities_df.sample(frac=0.1, random_state=42)  # 只采样一次
cv.fit(top3_cities_df_sample['text'])
print('number of `tokens`:', len(cv.vocabulary_))
cv.vocabulary_

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

number of `tokens`: 89453

{'thi': 79599,
 'place': 62402,
 'is': 44242,
 'ghetto': 37446,
 '.': 2403,
 'and': 11660,
 'as': 12778,
 'i': 42670,
 'complain': 24202,
 'to': 80372,
 'the': 79407,
 'bouncer': 17450,
 'that': 79384,
 'peopl': 60983,
 'were': 86374,
 'bump': 18793,
 'into': 44050,
 'me': 51379,
 'he': 40515,
 'said': 68988,
 'kept': 46132,
 'bark': 14640,
 'at': 12990,
 'them': 79465,
 'so': 73790,
 'wait-': 85396,
 'they': 79587,
 'are': 12482,
 'allow': 11064,
 'act': 9978,
 'like': 48464,
 'anim': 11778,
 'not': 56652,
 'say': 69959,
 'excus': 32440,
 'feel': 33554,
 'up': 83482,
 'my': 54658,
 'ass': 12908,
 'but': 19132,
 'wait': 85395,
 "'m": 632,
 'forget': 35229,
 'it': 44356,
 'go': 37927,
 'anoth': 11869,
 'classi': 23148,
 'loung': 49376,
 'skip': 73013,
 '!': 0,
 'amaz': 11320,
 'food': 34861,
 '...': 2405,
 'atmospher': 13079,
 '....': 2406,
 'owner': 59359,
 'wonder': 87349,
 'server': 71251,
 'also': 11176,
 'great': 38720,
 'we': 85960,
 'new': 55433,
 'neighborhood': 55260,
 'will': 86941,
 'be': 15027,
 'back': 13824,
 'veri': 84432,
 'soon': 74150,
 'love': 49411,
 ',': 1307,
 "'s": 899,
 'a': 9423,
 'byob': 19330,
 'senegales': 71103,
 'fri': 35800,
 'fish': 34123,
 'extra': 32660,
 'onion': 58065,
 'for': 35149,
 'sure': 77262,
 'couscou': 25285,
 'sometim': 74084,
 'lamb': 47356,
 'tough': 81042,
 'alway': 11229,
 'tasti': 78558,
 'enjoy': 31530,
 'juic': 45414,
 'when': 86577,
 'have': 40425,
 'well': 86175,
 'wa': 85285,
 'weekli': 86094,
 'costum': 25098,
 'of': 57378,
 'their': 79457,
 'until': 83418,
 'today': 80466,
 'went': 86362,
 'lunch': 49703,
 'employe': 31337,
 'told': 80555,
 'manag': 50431,
 'could': 25150,
 "n't": 54742,
 'chang': 21268,
 'or': 58339,
 'add': 10041,
 'anyth': 12054,
 'from': 36068,
 'sandwich': 69478,
 'month': 53710,
 'did': 28342,
 'never': 55409,
 'care': 20334,
 'had': 39640,
 'pay': 60621,
 'if': 42909,
 'special': 74705,
 'request': 67087,
 'normal': 56576,
 'she': 71762,
 'simpli': 72642,
 'complet': 24222,
 'refus': 66714,
 'lost': 49313,
 '4': 6743,
 'asham': 12813,
 'becaus': 15188,
 'person': 61257,
 'bar': 14415,
 'strang': 76238,
 'friend': 35876,
 'shant': 71661,
 'p': 59473,
 'do': 29175,
 'some': 74036,
 'hop': 41887,
 'birthday': 16311,
 'head': 40523,
 'downtown': 29701,
 'decid': 27320,
 'park': 60139,
 'huge': 42364,
 'free': 35578,
 'lot': 49314,
 '2nd': 6009,
 'n': 54735,
 'germantown': 37328,
 'catch': 20743,
 'el': 31056,
 'train': 81199,
 'down': 29644,
 'street': 76317,
 'walk': 85536,
 'suddenli': 76762,
 'need': 55185,
 'bathroom': 14867,
 'sheesh': 71792,
 '.with': 2611,
 'no': 55863,
 'in': 43218,
 'sight': 72533,
 'realli': 66265,
 'came': 19855,
 'across': 9972,
 'let': 48160,
 'just': 45538,
 'am': 11255,
 'hood': 41832,
 'grew': 38898,
 'hunt': 42507,
 'some.shadi': 74043,
 'etc': 32035,
 'gave': 37047,
 'damn': 26818,
 'creep': 25719,
 'there': 79522,
 'guy': 39486,
 'stand': 75531,
 'outsid': 58896,
 'block': 16679,
 'door': 29453,
 'look': 49189,
 'move': 54080,
 'unless': 83148,
 'somebodi': 74047,
 'made': 50044,
 'him': 41259,
 'use': 83718,
 'side': 72433,
 'bartend': 14717,
 'friendli': 35890,
 'order': 58403,
 'our': 58709,
 'usual': 83754,
 'draft': 29743,
 'pbr': 60671,
 'toward': 81098,
 '``': 9422,
 "''": 6,
 'size': 72895,
 'kindergartn': 46431,
 'cubbi': 26222,
 'hole': 41566,
 'clean': 23204,
 'though': 79788,
 'super': 77029,
 'dim': 28499,
 'light': 48383,
 'smell': 73465,
 'okay': 57669,
 'purs': 65102,
 'issu': 44338,
 'fit': 34204,
 'insid': 43834,
 'with': 87209,
 'close': 23369,
 'all': 10917,
 'crap': 25518,
 'on': 57905,
 'wall': 85584,
 'devil': 28191,
 'angel': 11725,
 'think': 79678,
 'photo': 61693,
 'rick': 67697,
 'ross': 68383,
 'huh': 42380,
 '?': 9366,
 'confus': 24452,
 'lol': 49054,
 'see': 70716,
 'kitchen': 46514,
 'menu': 51969,
 'blackboard': 16504,
 'promis': 64554,
 'even': 32151,
 'lead': 47779,
 'uh': 82333,
 'thank': 79363,
 'patron': 60563,
 'most': 53943,
 'local': 48922,
 'get': 37355,
 'off': 57395,
 'work': 87497,
 'bothersom': 17359,
 'tabl': 77824,
 'same': 69367,
 'sit': 72830,
 'hi': 41046,
 'half': 39761,
 'beer': 15317,
 'like.it': 48473,
 'been': 15306,
 'day': 27056,
 'along': 11134,
 'multipl': 54378,
 'dispos': 28980,
 'cell': 20994,
 'phone': 61668,
 'clearli': 23270,
 'sell': 70919,
 'someth': 74065,
 'random': 65843,
 'folk': 34810,
 'speak': 74674,
 'leav': 47827,
 'ye': 88150,
 'exchang': 32420,
 'hand': 39975,
 'ai': 10561,
 'direct': 28710,
 'dive': 29081,
 'shadi': 71557,
 'good': 38140,
 'drink': 29866,
 'ca': 19416,
 'frequent': 35697,
 'cross': 25941,
 'between': 15954,
 'rap': 65873,
 'concert': 24327,
 'seanc': 70546,
 'want': 85661,
 'dealer': 27211,
 'conduct': 24403,
 'busi': 19049,
 'nice': 55575,
 'littl': 48749,
 'awesom': 13510,
 'gyro': 39535,
 'pizza': 62291,
 'ok': 57649,
 '..': 2404,
 'by': 19301,
 'slice': 73161,
 'price': 64225,
 'too': 80717,
 'favorit': 33440,
 'coffe': 23676,
 'shop': 72080,
 "'re": 864,
 'commun': 24122,
 'centric': 21035,
 'offer': 57453,
 'produc': 64471,
 'product': 64480,
 'healthi': 40583,
 'soup': 74350,
 'snack': 73622,
 'whatnot': 86522,
 'host': 42016,
 'after': 10312,
 'hour': 42156,
 'event': 32162,
 'which': 86616,
 'provid': 64702,
 'forum': 35324,
 'share': 71682,
 'idea': 42869,
 'content': 24627,
 'pertain': 61283,
 'solidar': 74000,
 'margin': 50776,
 'voic': 84939,
 'fuck': 36265,
 'magic': 50114,
 'crab': 25392,
 'rangoon': 65859,
 'more': 53808,
 'cream': 25619,
 'chees': 21599,
 'than': 79354,
 'honey': 41761,
 'chicken': 22007,
 'cheap': 21486,
 'fatti': 33387,
 'schezchuan': 70148,
 'beef': 15257,
 'terribl': 79179,
 'wateri': 85854,
 'sauc': 69756,
 'everi': 32223,
 'piec': 61907,
 'meat': 51471,
 'tendon': 79046,
 'overpr': 59249,
 'bad': 13963,
 'qualiti': 65263,
 'pictur': 61874,
 'review': 67467,
 'eat': 30602,
 'immedi': 43086,
 'ridicul': 67733,
 'you': 88492,
 'delici': 27670,
 'burger': 18890,
 'pleas': 62685,
 'here': 40925,
 'classic': 23149,
 'bacon': 13917,
 'garlic': 36890,
 'parm': 60177,
 'tell': 78937,
 'perfect': 61126,
 'mean': 51447,
 'put': 65129,
 'enough': 31558,
 '(': 1205,
 'steak': 75762,
 ')': 1206,
 'remain': 66905,
 'crispi': 25830,
 'few': 33742,
 'differ': 28404,
 'bottl': 17371,
 'yay': 88126,
 'touristi': 81082,
 'thing': 79658,
 'trip': 81500,
 'stop': 76120,
 'market': 50838,
 'amish': 11525,
 'item': 44448,
 'intox': 44055,
 'fragranc': 35437,
 'everywher': 32292,
 'your': 88539,
 'first': 34087,
 'time': 80113,
 'around': 12641,
 'what': 86493,
 'befor': 15457,
 'commit': 24108,
 'one': 57980,
 'regret': 66754,
 'tri': 81422,
 'other': 58656,
 'varieti': 84062,
 'can': 19914,
 'jam': 44719,
 'jerki': 45034,
 'poboy': 62846,
 'butcher': 19140,
 'cut': 26515,
 'much': 54201,
 'cool': 24805,
 'quaint': 65250,
 'locat': 48962,
 'imagin': 43048,
 'deli': 27639,
 '20': 5384,
 'year': 88172,
 'ago': 10450,
 'ran': 65816,
 'older': 57760,
 'coupl': 25236,
 'everyth': 32271,
 'hard': 40197,
 'read': 66212,
 ':': 9326,
 'best': 15833,
 'way': 85909,
 'knew': 46601,
 'regular': 66763,
 'vibe': 84574,
 'give': 37696,
 'authent': 13307,
 'who': 86749,
 'about': 9693,
 'final': 33928,
 'how': 42249,
 'then': 79491,
 'wander': 85650,
 'small': 73370,
 'groceri': 39033,
 'store': 76142,
 'select': 70810,
 'chip': 22309,
 'dessert': 28071,
 'sat': 69695,
 'reuben': 67435,
 'german': 37319,
 'potato': 63524,
 'salad': 69041,
 'definit': 27526,
 'repeat': 67018,
 'especi': 31913,
 'treat': 81334,
 'human': 42399,
 'serv': 71236,
 'prepar': 64065,
 'belovedli': 15632,
 'begrudgingli': 15487,
 'reserv': 67119,
 'saturday': 69742,
 '11/01/2014': 3801,
 'experi': 32541,
 'aw': 13472,
 'quit': 65530,
 'honest': 41754,
 'disappoint': 28755,
 'kind': 46419,
 'establish': 31985,
 "'ve": 1128,
 'experienc': 32545,
 'better': 15916,
 'servic': 71297,
 'truck': 81616,
 'celebr': 20977,
 'night': 55672,
 'onli': 58095,
 'ruin': 68612,
 'lack': 47213,
 'seat': 70602,
 'smile': 73485,
 'hostess': 42030,
 'henc': 40868,
 'whi': 86615,
 'two': 82070,
 'star': 75588,
 'rather': 65970,
 'given': 37701,
 'took': 80767,
 'minut': 52930,
 'brought': 18307,
 'us': 83679,
 'kid': 46307,
 'industri': 43564,
 'shiraz': 71943,
 'dogfish': 29259,
 'should': 72189,
 'taken': 78092,
 'long': 49101,
 'patient': 60525,
 'ignor': 42933,
 'check': 21526,
 'next': 55514,
 '--': 1325,
 'god': 37995,
 'forbid': 35179,
 'parti': 60259,
 'forti': 35309,
 'five': 34229,
 'togeth': 80515,
 'dish': 28877,
 'gener': 37204,
 'tip': 80239,
 ';': 9340,
 'still': 76000,
 'left': 47904,
 'foul': 35349,
 'tast': 78499,
 'mouth': 54054,
 'xix': 87935,
 'driven': 29981,
 'mani': 50568,
 'readi': 66220,
 'fanci': 33132,
 'ani': 11776,
 'sketch': 72962,
 'wether': 86438,
 'front': 36096,
 'both': 17352,
 'counter': 25178,
 'make': 50254,
 'own': 59352,
 '6': 7750,
 'inch': 43350,
 'cuban': 26194,
 '5': 7277,
 '$': 2,
 '12': 4038,
 'bbq': 14980,
 'wing': 87078,
 'meatbal': 51555,
 'sub': 76600,
 'fountain': 35362,
 'machin': 49976,
 'carbon': 20283,
 'out': 58724,
 'soda': 73856,
 'tea': 78751,
 'ok.': 57658,
 'take': 78069,
 'would': 87616,
 'come': 24019,
 'bread': 17764,
 'decor': 27361,
 'ambianc': 11387,
 'true': 81633,
 'divey': 29103,
 'type': 82157,
 'overal': 59108,
 'urg': 83657,
 'cafe': 19527,
 'step': 75900,
 'lower': 49550,
 'attent': 13154,
 'south': 74432,
 'famou': 33105,
 'spot': 75107,
 'sss': 75365,
 'distanc': 29037,
 'hundr': 42473,
 'cart': 20529,
 'although': 11202,
 'ha': 39578,
 '6.50': 7833,
 'either': 31041,
 'game': 36729,
 'fresh': 35706,
 'excit': 32422,
 'someon': 74055,
 '30': 6317,
 '%': 3,
 'sadli': 68930,
 'unevit': 82953,
 'sweet': 77507,
 'seem': 70747,
 'inventori': 44103,
 'actual': 9999,
 'hope': 41894,
 'doe': 29224,
 'suggest': 76819,
 'purchas': 65057,
 'last': 47555,
 'week': 86061,
 'staff': 75413,
 '10': 3366,
 'face': 32846,
 'cant': 20051,
 'decent': 27303,
 'lose': 49309,
 'money': 53609,
 'custom': 26487,
 'luck': 49629,
 'advic': 10210,
 'bring': 18108,
 'restaur': 67209,
 'an': 11603,
 'institut': 43916,
 '5/5': 7448,
 'everyon': 32262,
 'profession': 64497,
 'melt': 51868,
 'visit': 84838,
 'weekend': 86083,
 'area': 12489,
 'claim': 23102,
 'noth': 56790,
 'bravo': 17736,
 'bern': 15765,
 'bland': 16550,
 'sh': 71515,
 '*': 1207,
 'tti': 81757,
 'waitress': 85468,
 'ad': 10022,
 'her': 40893,
 'credit': 25712,
 'avoid': 13463,
 "'ll": 619,
 'least': 47815,
 '2-3': 5142,
 'now': 56862,
 'thought': 79795,
 'extrem': 32702,
 'mess': 52124,
 'vegetarian': 84232,
 'option': 58320,
 'unfortun': 82994,
 'gluten': 37858,
 'got': 38391,
 'kale': 45722,
 'quinoa': 65509,
 'cook': 24731,
 'ask': 12861,
 'suppos': 77229,
 'recommend': 66473,
 'entre': 31643,
 'i\u200b': 44547,
 'cox': 25353,
 'seafood': 70500,
 'live': 48773,
 'town': 81103,
 'far': 33211,
 'away': 13484,
 'cases\u200b': 20594,
 'too\u200b\u200b\u200b': 80811,
 'is\u200b': 44355,
 '\u200blarg': 89324,
 'refriger': 66701,
 'case': 20583,
 'abndanc': 9671,
 'lobster': 48901,
 'impress': 43182,
 'whole': 86765,
 'gut': 39470,
 'descaled\u200b': 27986,
 'plan': 62497,
 'lemon': 47976,
 'thyme': 79983,
 'includ': 43364,
 'reasonable\u200b': 66327,
 'publix': 64871,
 'due': 30181,
 'financi': 33935,
 'switch': 77632,
 'fan': 33108,
 'mayb': 51191,
 'where': 86585,
 'pasco': 60329,
 'longest': 49152,
 'closest': 23393,
 'ingredi': 43694,
 'onc': 57956,
 'gone': 38119,
 'unabl': 82535,
 'find': 33939,
 'specif': 74750,
 'quick': 65444,
 'point': 62892,
 'substitut': 76669,
 'advis': 10213,
 'subtl': 76677,
 'expect': 32501,
 'finish': 33991,
 'problem': 64432,
 'answer': 11883,
 'stupid': 76541,
 'noob': 56481,
 'question': 65418,
 'clear': 23254,
 'tap': 78333,
 'room': 68277,
 'these': 79568,
 'occas': 57270,
 'respect': 67174,
 'load': 48878,
 'grant': 38579,
 'till': 80097,
 'retail': 67373,
 'killer': 46371,
 'core': 24907,
 'veteran': 84543,
 'craft': 25464,
 'drinker': 29893,
 'bud': 18583,
 'lite': 48718,
 'equal': 31755,
 'agreeabl': 10463,
 'brew': 17955,
 'otherwis': 58671,
 'style': 76561,
 'sour': 74402,
 'obscur': 57229,
 'continent': 24641,
 'european': 32116,
 'recip': 66426,
 'binder': 16249,
 'extract': 32684,
 'grain': 38504,
 'know': 46651,
 'sign': 72542,
 'class': 23142,
 '1.': 3179,
 '2.': 5217,
 '3.': 6137,
 'learn': 47807,
 '4.': 6822,
 'support': 77223,
 'wife': 86876,
 'entir': 31616,
 'describ': 27994,
 'damp': 26828,
 'musti': 54615,
 'tender': 79025,
 'slow': 73287,
 'crowd': 25987,
 'ugggg': 82311,
 'north': 56597,
 'indian': 43460,
 'cuisin': 26274,
 'short': 72127,
 'hardcor': 40239,
 'foodi': 35049,
 'remind': 66932,
 'delhi': 27637,
 'wo': 87285,
 'bay': 14922,
 'hookah': 41844,
 'uniqu': 83095,
 'ice': 42792,
 'tube': 81769,
 'concept': 24311,
 'sushi': 77333,
 'burrito': 19005,
 'environ': 31695,
 'bowl': 17521,
 'past': 60388,
 'fat': 33340,
 'ladi': 47257,
 'automat': 13339,
 'awe': 13502,
 'calm': 19795,
 'yet': 88329,
 'bright': 18074,
 'enter': 31594,
 'almost': 11106,
 'full': 36326,
 'old': 57721,
 'breweri': 17975,
 'pack': 59574,
 'brim': 18098,
 'fill': 33875,
 'convers': 24695,
 'laughter': 47667,
 'fun': 36387,
 'board': 16849,
 'again': 10370,
 'end': 31439,
 'manayunk': 50469,
 'uno': 83202,
 'connect': 24493,
 'four': 35366,
 'scrabbl': 70356,
 'f': 32780,
 'ck': 23088,
 'w.': 85074,
 'philli': 61540,
 '4.75': 6882,
 'over': 58966,
 'pound': 63621,
 'previous': 64208,
 'heard': 40611,
 'choo': 22572,
 'pho': 61625,
 'notic': 56805,
 'right': 67769,
 'plung': 62789,
 'upon': 83565,
 'spread': 75148,
 '25': 5769,
 'addit': 10070,
 'base': 14769,
 'carb': 20251,
 'rice': 67625,
 'noodl': 56484,
 'lo': 48871,
 'mein': 51797,
 'basic': 14790,
 'assembl': 12922,
 'line': 48583,
 'pick': 61806,
 'subsequ': 76654,
 'itself': 44481,
 'less': 48110,
 'greasi': 38703,
 'version': 84495,
 'panda': 59867,
 'express': 32618,
 'slightli': 73195,
 'pig': 61960,
 'feet': 33571,
 'tomato': 80591,
 'egg': 30884,
 'seawe': 70647,
 'mom': 53527,
 'bit': 16376,
 'skeptic': 72961,
 'saw': 69936,
 'meal': 51403,
 'write': 87712,
 'stomach': 76086,
 'lukewarm': 49671,
 'uncomfort': 82669,
 'sinc': 72666,
 'takeout': 78097,
 'heat': 40652,
 'consum': 24598,
 'somewher': 74093,
 'atroci': 13130,
 'haha': 39682,
 'unhealthi': 83036,
 'portion': 63314,
 'keep': 46042,
 'return': 67420,
 'famili': 33054,
 '7.': 8209,
 'name': 54868,
 'flat': 34373,
 'handl': 40059,
 'felt': 33610,
 'larg': 47504,
 'rude': 68577,
 '120': 4181,
 'dollar': 29308,
 'worth': 87598,
 'gift': 37519,
 'card': 20296,
 'spend': 74809,
 'turn': 81927,
 'ate': 13008,
 'patti': 60583,
 'whack': 86477,
 'fantast': 33186,
 'howev': 42262,
 'wine': 87026,
 'ahi': 10541,
 'tuna': 81848,
 'appet': 12209,
 'mediocr': 51659,
 'salmon': 69179,
 'phenomen': 61452,
 'reason': 66316,
 'hyde': 42611,
 'dinner': 28610,
 'list': 48695,
 'endless': 31462,
 'detail': 28141,
 'pretti': 64175,
 "'hood": 527,
 'wow': 87633,
 'i.e': 42732,
 'wm': 87277,
 'mulherin': 54320,
 'set': 71418,
 'apart': 12101,
 'falafel': 32984,
 'joint': 45263,
 'stellar': 75887,
 'belgian-styl': 15563,
 'french': 35657,
 'cone': 24407,
 '#': 1,
 'dammit': 26815,
 'garnish': 36938,
 'stuff': 76509,
 'fast': 33303,
 'insan': 43813,
 'satisfi': 69724,
 'kaleisia': 45733,
 'picki': 61830,
 'studi': 76491,
 'overwhelm': 59326,
 'frankli': 35499,
 'eaten': 30630,
 'vegan': 84153,
 'rock': 68069,
 'bake': 14124,
 'buy': 19255,
 'randomli': 65844,
 'privat': 64380,
 'dure': 30323,
 'lame': 47380,
 'convinc': 24717,
 'call': 19756,
 'stay': 75741,
 'nearbi': 55132,
 'hotel': 42107,
 'promptli': 64564,
 'appropri': 12331,
 'temperatur': 78972,
 'american': 11459,
 'ever': 32181,
 'might': 52544,
 'pepper': 61025,
 'crisp': 25817,
 'boneless': 17085,
 'averag': 13399,
 'none': 56428,
 '7pm': 8557,
 '3': 6047,
 'slate': 73107,
 'ident': 42879,
 'crisi': 25815,
 'tacki': 77923,
 'cold': 23820,
 'bug': 18667,
 'im': 43037,
 'sorri': 74269,
 'truli': 81656,
 'believ': 15577,
 'shouldnt': 72202,
 'swing': 77615,
 'dine': 28533,
 'separ': 71154,
 '-': 1324,
 'overcook': 59141,
 'consid': 24547,
 'cliantro': 23296,
 'cajun': 19617,
 'popcorn': 63142,
 'po': 62830,
 "'": 5,
 'boy': 17560,
 'stuf': 76507,
 'truffl': 81641,
 'brunch': 18387,
 '&': 4,
 'waffl': 85348,
 'die': 28360,
 'shrimp': 72261,
 'grit': 39005,
 'bone': 17076,
 'pork': 63214,
 'chop': 22580,
 'mac': 49911,
 'juici': 45448,
 'alfredo': 10861,
 'drizzl': 29992,
 'goe': 38027,
 'heavili': 40687,
 'season': 70567,
 'probabl': 64418,
 'oil': 57602,
 'potenti': 63578,
 '8': 8575,
 'arriv': 12681,
 '7:30': 8496,
 '5-6': 7300,
 'water': 85823,
 'rest': 67193,
 'trickl': 81459,
 '30-45': 6332,
 'without': 87234,
 'beverag': 15971,
 '20-30': 5399,
 'anyon': 12047,
 'girl': 37660,
 'advertis': 10206,
 'each': 30464,
 '7': 8165,
 'inquir': 43800,
 'pass': 60339,
 'wrong': 87727,
 'fishi': 34170,
 ...}

**First, I tried to do bow to see if using word frequency alone would produce better results. My guess is that in restaurant reviews, there aren’t many words whose meanings change depending on the context, so bow shouldn’t be a big problem. I chose the clusters obtained in the m1 stage as labels because they had a good f1 score at the time and there were no better labels available.**

**Here, the data crashed several times and it took about half an hour to get the results. The reason is that we had 1370k of data, which was too much for colab to handle, so we sampled 10%.**

In [10]:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(top3_cities_df_sample, test_size=0.2, random_state=42)

dtmt = cv.transform(df_train['text'])
dtmte = cv.transform(df_test['text'])


classifier = LogisticRegression(max_iter=1000)
classifier.fit(dtmt, df_train['cluster'])

y_pred_bow = classifier.predict(dtmte)
accuracy_bow = accuracy_score(df_test['cluster'], y_pred_bow)
f1_bow = sklearn.metrics.f1_score(df_test['cluster'], y_pred_bow, average='weighted')

print(f"Accuracy (BoW): {accuracy_bow}")
print(f"F1 Score (BoW): {f1_bow}")
print(classification_report(df_test['cluster'], y_pred_bow))

labels = df_test['cluster'].unique()
display(pd.DataFrame(confusion_matrix(df_test['cluster'], y_pred_bow, normalize='true'), columns=labels, index=labels))

Accuracy (BoW): 0.4764373060777514
F1 Score (BoW): 0.4720065960827968
              precision    recall  f1-score   support

           0       0.42      0.29      0.35      2325
           1       0.39      0.33      0.36      5904
           2       0.57      0.54      0.56      8935
           3       0.45      0.56      0.50     10037
           4       0.18      0.11      0.13       189
           5       0.00      0.00      0.00         5

    accuracy                           0.48     27395
   macro avg       0.34      0.30      0.32     27395
weighted avg       0.48      0.48      0.47     27395

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

          1         3         2         0         4         5
1  0.293763  0.168602  0.095914  0.440860  0.000860  0.000000
3  0.044885  0.329438  0.165650  0.458841  0.001186  0.000000
2  0.019922  0.100839  0.537661  0.335534  0.005932  0.000112
0  0.048520  0.168078  0.222278  0.557936  0.003089  0.000100
4  0.010582  0.037037  0.634921  0.211640  0.105820  0.000000
5  0.000000  0.000000  0.600000  0.400000  0.000000  0.000000

**But the results show that bow's data is not reliable, which means that there may be some changes in word meaning that I did not expect. Based on this result, I plan to try TF-IDF again.**

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(tokenizer=tokenize_lemmatize)
tfidf.fit(top3_cities_df_sample['text'])

dtmt_tfidf = tfidf.transform(df_train['text'])
dtmte_tfidf = tfidf.transform(df_test['text'])

print('number of `tokens`:', len(tfidf.vocabulary_))

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

number of `tokens`: 89453

In [12]:
print(df_train.columns)
print(df_test.columns)

Index(['review_id', 'user_id', 'business_id', 'stars_review', 'useful',
       'funny', 'cool', 'text', 'date', 'name', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars_business',
       'review_count', 'is_open', 'attributes', 'categories', 'hours',
       'name_user', 'review_count_user', 'yelping_since', 'useful_user',
       'funny_user', 'cool_user', 'elite', 'friends', 'fans', 'average_stars',
       'compliment_hot', 'compliment_more', 'compliment_profile',
       'compliment_cute', 'compliment_list', 'compliment_note',
       'compliment_plain', 'compliment_cool', 'compliment_funny',
       'compliment_writer', 'compliment_photos', 'active_years', 'elite_count',
       'elite_flag', 'friends_count', 'compliment_total', 'cluster'],
      dtype='object')
Index(['review_id', 'user_id', 'business_id', 'stars_review', 'useful',
       'funny', 'cool', 'text', 'date', 'name', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars_business',
       'review_count', 'is_open', 'attributes', 'categories', 'hours',
       'name_user', 'review_count_user', 'yelping_since', 'useful_user',
       'funny_user', 'cool_user', 'elite', 'friends', 'fans', 'average_stars',
       'compliment_hot', 'compliment_more', 'compliment_profile',
       'compliment_cute', 'compliment_list', 'compliment_note',
       'compliment_plain', 'compliment_cool', 'compliment_funny',
       'compliment_writer', 'compliment_photos', 'active_years', 'elite_count',
       'elite_flag', 'friends_count', 'compliment_total', 'cluster'],
      dtype='object')

**There are a lot of bugs here. I checked the column name to ensure our work is OK.**

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import pandas as pd

classifier_tfidf = LogisticRegression(max_iter=1000)
classifier_tfidf.fit(dtmt_tfidf, df_train['cluster'])

y_pred_tfidf = classifier_tfidf.predict(dtmte_tfidf)

accuracy_tfidf = accuracy_score(df_test['cluster'], y_pred_tfidf)
f1_tfidf = f1_score(df_test['cluster'], y_pred_tfidf, average='weighted')

print(f"Accuracy (TF-IDF): {accuracy_tfidf}")
print(f"F1 Score (TF-IDF): {f1_tfidf}")
print(classification_report(df_test['cluster'], y_pred_tfidf))
display(pd.DataFrame(confusion_matrix(df_test['cluster'], y_pred_tfidf, normalize='true'),
                     columns=classifier_tfidf.classes_, index=classifier_tfidf.classes_))

Accuracy (TF-IDF): 0.5122832633692279
F1 Score (TF-IDF): 0.5025435102012773
              precision    recall  f1-score   support

           0       0.51      0.33      0.40      2325
           1       0.46      0.32      0.38      5904
           2       0.57      0.64      0.60      8935
           3       0.48      0.57      0.52     10037
           4       0.00      0.00      0.00       189
           5       0.00      0.00      0.00         5

    accuracy                           0.51     27395
   macro avg       0.34      0.31      0.32     27395
weighted avg       0.51      0.51      0.50     27395

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

          0         1         2         3    4    5
0  0.332043  0.122151  0.106667  0.439140  0.0  0.0
1  0.041159  0.319953  0.202236  0.436653  0.0  0.0
2  0.010520  0.062003  0.637605  0.289871  0.0  0.0
3  0.040749  0.133406  0.260337  0.565508  0.0  0.0
4  0.005291  0.000000  0.830688  0.164021  0.0  0.0
5  0.000000  0.000000  0.800000  0.200000  0.0  0.0

**Although not outstanding, this model clearly performs better than bow, so it is likely that some of the high-frequency words have no real meaning.**

In [14]:
!pip install mglearn

Requirement already satisfied: mglearn in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from mglearn) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from mglearn) (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from mglearn) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from mglearn) (2.2.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from mglearn) (11.1.0)
Requirement already satisfied: cycler in /usr/local/lib/python3.11/dist-packages (from mglearn) (0.12.1)
Requirement already satisfied: imageio in /usr/local/lib/python3.11/dist-packages (from mglearn) (2.37.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from mglearn) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (1.3.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->mglearn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->mglearn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->mglearn) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->mglearn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->mglearn) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->mglearn) (1.17.0)

In [15]:
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer
import mglearn
import numpy as np

vectorizer = TfidfVectorizer(max_features=300)
X_tfidf = vectorizer.fit_transform(top3_cities_df_sample["text"])

model = NMF(n_components=5, random_state=42)
model.fit(X_tfidf)

word_importance = model.components_ / model.components_.sum(axis=0, keepdims=True)
feature_names = vectorizer.get_feature_names_out()

mglearn.tools.print_topics(topics=range(5), feature_names=feature_names,
                          sorting=np.argsort(word_importance, axis=1)[:, ::-1], n_words=10,
                           topics_per_chunk=1)

topic 0
--------
best
city
the
most
area
side
pork
beef
ever
top


topic 1
--------
was
ok
wasn
tasted
cooked
ordered
overall
got
it
again


topic 2
--------
great
friendly
atmosphere
awesome
always
staff
selection
love
amazing
recommend


topic 3
--------
our
we
us
minutes
table
server
told
waitress
she
her


topic 4
--------
you
re
want
your
don
if
need
do
get
know

/usr/local/lib/python3.11/dist-packages/sklearn/decomposition/_nmf.py:1742: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

**Judging from the results, this grouping should be successful. For example, topic 0 is obviously talking about geographical location and things themselves, while topic 1 contains many neutral words, which should be a less extreme conclusion. etc. The final conclusion is that there are several major categories of topics that users like to comment on: "location and food", "neutral thoughts", "good atmosphere", "personal experience", "warning"**

In [17]:
from sklearn.decomposition import PCA
import plotly.express as px
import pandas as pd

topic_embeddings = model.components_

pca = PCA(n_components=3, random_state=42)
topic_embeddings_3d = pca.fit_transform(topic_embeddings)

df_topics = pd.DataFrame(topic_embeddings_3d, columns=['x', 'y', 'z'])
df_topics['topic'] = ["location and food", "neutral thoughts", "good atmosphere", "personal experience", "warning"]

fig = px.scatter_3d(df_topics, x='x', y='y', z='z', text='topic', title="Topic Relationship in 3D")
fig.show()

**After selecting the model with better performance, we performed dimensionality reduction to see if these topics would be significantly close or have other unusual patterns. The results showed that the grouping of this topic was successful, and there was no obvious classification problem.**

In [ ]:
from scipy.cluster.hierarchy import linkage
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import fcluster
topic_scores_test = model.transform(vectorizer.transform(top3_cities_df_sample['text']))
linkage_matrix_topics = linkage(topic_scores_test, method='ward')
sil_topics = silhouette_score(topic_scores_test, fcluster(linkage_matrix_topics, 5, criterion='maxclust'))
print(f"Silhouette Score (Topic Modeling): {sil_topics}")

**This part crashed 4 times and we run out of time to rerun the whole notebook again. The conclusion here should be able to confirm whether our model can be applied to subsequent text analysis.**

**Each crash will take about 50 minutes, and the cause of the crash has never been found. We really can't run the final result.**

**But combined with the above analysis, we can know that this model must be logically correct, and the final uncertainty is just to test how much new data it can cover. When you encounter more reviews in the future, you can use this method to classify user comments and understand their tendencies and dissatisfaction.**